name: Cypress Tests with Install Job and UI Chrome Job x 5

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]
jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.17.0-chrome106
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      # - name: Save build folder
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: build
      #     if-no-files-found: error
      #     path: .

  ui-chrome-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    needs: install
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v4
        with:
          # we have already installed all dependencies above
          # install: false
          # start: npm run cy:happypath
          # wait-on: 'http://localhost:3000'
          # wait-on-timeout: 120
          browser: chrome
          config-file: additional.config.js
          # record: true
          # parallel: true
          # group: 'UI - Chrome'
          spec: cypress/e2e/1-getting-started/todo.cy.js

      - name: Download the screenshots folders
        uses: actions/download-artifact@v2
        with:
          name: screenshots
          if-no-files-found: warn
          path: cypress/screenshots

      - name: Download the videos folders
        uses: actions/download-artifact@v2
        with:
          name: videos
          if-no-files-found: warn
          path: cypress/videos

        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}